### ISSUE TITLE
[Bug] Setting paths in json config does not link properly

### ISSUE THREAD

**Issue by Hafler** [ebullient/ttrpg-convert-cli#103]
**Version**: 1.1.1

**Issue**:
Perhaps I am just misunderstanding the configuration steps. I would like to move all generated content into /References/Compendium/ and /References/Rules, as i have a particualr organization structure for my vault. When I use the following configuration, the files are generated in the appropriate directory, but the links still point at /Compendium/ and /Rules/ respectively instead of as subdirectories under /References/. 

```
{
  "from": [
    "PHB",
    "EGW"
  ],
  "paths": {
    "compendium": "/References/Compendium/",
    "rules": "/References/Rules/"
  }
}
```

If I then open up a bestiary note of a monster that causes a condition, the links for that condition are to /Rules/conditions.md

Any help would be greatly appreciated. Wonderful work on this!

**Comment by Hafler** [comment]
Ah i figured it out the -o is to the root vault directory. Paths in the config for the subdirectories.

**Comment by ebullient** [comment]
yes! Does that mean you're good? Wording I should fix? (PR for the readme if you needed a hint in a certain place would be great!)

**Comment by Hafler** [comment]
Yeah, I think I'm good. The following should probably be updated in the readme:

1. It looks like the readme still mentions 5e-convert, but releases are for ttrpg-convert
2. Perhaps a simple note for the paths config setting saying that it's the path below the -o flag instead of saying root of your vault. I wrongly assume that the code somehow navigated upward until it saw a .obsidian directory or something.

Other than that. Fantastic tool!
