### ISSUE TITLE
[FR]: Provide option for fully qualified or partially qualified directories

### ISSUE THREAD

**Issue by namtrah** [ebullient/ttrpg-convert-cli#106]
I notice that when I do not put the root folder (name it "compendium") into the root of my vault, none of the wikilinks nor pictures work, because of the preceding `/` in the file name automatically generated by the tool.

By removing this, Obsidian finds the image, or file without an issue. I do not want to change the default behaviour (as many of you do use it in your root directory), but would it be possible to have an option to turn on|off manually the use of the initial forward slash

This would greatly help me as finding & replacing these are tedious due to different directory names (like rules, bestiary, etc.)

**Comment by ebullient** [comment]
my concern is that relative links between compendium and rules (depending on where you put them) don't work

You can specify where your compendium folder is.. so it is generated with all of everything in the right place (in which case, the leading / is fine)

Alternately, bring compendium & rules into your folder at the root level. And move them within obsidian (which will convert/update all links.. but will make later merging a mess).

```
    "paths" : {
      "compendium" : "/my/vault/path/to/compendium/",
      "rules" : "/my/vault/path/to/rules/"
    },
```

**Comment by namtrah** [comment]
Well, I have tried to replace manually,  `/compendium/...` with `compendium/...` and `/rules/...` with `rules/...` and everything seems to work just fine.

Yes, I can work with setting path entry that way. I just thought if you needed some practical experience with it that it works even without the leading slash as far as I can tell.

**Comment by ebullient** [comment]
The leading slash will be removed in 1.3.0
