### ISSUE TITLE
Add two spaces to the beginning of any tags

### ISSUE THREAD

**Issue by namtrah** [ebullient/ttrpg-convert-cli#107]
The YAML format is very strict with regards to formatting, afaiu. I have been told I should use only a set number of spaces versus anything else. It seems to me that even starting a tag at the beginning of the line is also not YAML conform. Such as the following:

```yaml
tags:
- tag1
- tag2
```

Can I make a suggestion to modify this so that there are always two spaces (or however many the actual format requires) before the `-` sign? Such as:

```yaml
tags:
  - tag1
  - tag2
```

**Comment by ebullient** [comment]
both of the above are valid yaml syntax.

**Comment by namtrah** [comment]
OK. I just seem to get "Invalid YAML" in obsidian often. Maybe I can upload a visual.
![image](https://user-images.githubusercontent.com/13903735/228062955-6d560dfb-9603-471b-aa01-d7e57c140368.png)

**Comment by namtrah** [comment]
Never mind. I see that it does seem to work. Then it is just a user preference of mine for readability. But I can then see this as closed and WAD.
