### ISSUE TITLE
Unconverted text in Markdown files

### ISSUE THREAD

**Issue by XintakXVI** [ebullient/ttrpg-convert-cli#116]
Hello! First off, thanks for such a great tool!

I noticed that in many of the resulting Markdown files, there are instances of text of the form `{@something somethingelse}` which I believe were supposed to be converted to links. For example, the file `conjure-elemental.md` in `/compendium/spells` has `{@status concentration}`, instead of linking to `/rules/status.md##Concentration` (I think).
I have no experience with Java, but after a long search, maybe it could be related to the [JsonSource.java](https://github.com/ebullient/ttrpg-convert-cli/blob/main/src/main/java/dev/ebullient/convert/tools/dnd5e/JsonSource.java) file, as I don't see a pattern to match for `{@status concentration}`.

**Comment by ebullient** [comment]
yes. I think I have a patch for `{@status... }` .. which is a recent change.

I'll have to see what else they've added. I am guessing that is why this build failed: https://github.com/ebullient/ttrpg-convert-cli/actions/runs/4643110420

**Comment by ebullient** [comment]
I did have a patch for {@status .. }... I have a few others to chase, then will cut a release to resolve this.

**Comment by ebullient** [comment]
This should be resolved in the 2.0 release.
