### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by XintakXVI** [ebullient/ttrpg-convert-cli#117]
Some of the links in the Markdown files have a missing `/`, so it points to a file that doesn't exist.
As an example, the `conjure-elemental.md` file in `/compendium/spells` has the link `[fire elemental](/compendium/bestiaryelemental/fire-elemental.md)`, which doesn't exist because it's missing a slash to separate `bestiary` and `elemental`. The correct link would be `/compendium/bestiary/elemental/fire-elemental.md)`, which points to an actually existing file.

This problem seems to have occurred exclusively with links to the bestiary.

**Comment by ebullient** [comment]
Thanks for the heads up. Will have a look

**Comment by ebullient** [comment]
I can't replicate this. Can you please confirm which version of the CLI you're using, and which sources you have enabled?

**Comment by XintakXVI** [comment]
How do I check what version of the CLI I'm using? 😅

**Comment by ebullient** [comment]
depending on how you invoke it, use the --version option.

**Comment by XintakXVI** [comment]
Version is 1.1.1, and I believe the sources were PHB and MM.

**Comment by ebullient** [comment]
When I do this with the MM present, I get this: 

```
You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it. For example, a [fire elemental](/compendium/bestiary/elemental/fire-elemental.md) emerges from a bonfire, and an [earth elemental](/compendium/bestiary/elemental/earth-elemental.md) rises up from the ground. The elemental disappears when it drops to 0 hit points or when the spell ends.
```

When the MM is not present, I get this: 

```
You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the area you chose appears in an unoccupied space within 10 feet of it. For example, a fire elemental emerges from a bonfire, and an earth elemental rises up from the ground. The elemental disappears when it drops to 0 hit points or when the spell ends.
```

**Comment by XintakXVI** [comment]
> Are you using windows?
Yes I am

> How comfortable are you with the command line and/or building software?
I've used CLI tools before, but I'm not very familiar with developing software 😅

Anyway, it seems like everything is fixed now, so cheers I guess?
