### ISSUE TITLE
[Bug][PF2E]: Some Tags have Spaces

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/ttrpg-convert-cli#149]
Some traits have spaces, and these are not being properly sluggified when converted into Obsidian Tag format.

#### Alignment
Chaotic Evil
Chaotic Neutral
Chaotic Good
Lawful Evil
Lawful Neutral
Lawful Good
Neutral Evil
Neutral Good

#### Class
Any Class

#### Combat
Certain Kill

#### Creature
Sea Devil

#### General
Pervasive Magic
True Name

#### Gravity
High Gravity
Low Gravity
Strange Gravity
Subjective Gravity

### Item
Shield Throw

### Planar
(Repeats Gravity Ones)

### Tradition
Any Magical Tradition

### Weapon
Critical Fusion
Double Barrel
Fatal Aim
Range Increment
Ranged Trip

**Comment by sigrunixia** [comment]
Adding to this.

Because the tags created on the index are not nested tags, tax explorer experiences a great amount of "tag spam". 

<img width="322" alt="image" src="https://github.com/ebullient/ttrpg-convert-cli/assets/68425372/4d7fcf84-c786-4213-aaf5-0915cc0f9ddc">

**Comment by ebullient** [comment]
will have to find the culprit
