### ISSUE TITLE
Example configs do not work

### ISSUE THREAD

**Issue by DrakeRichards** [ebullient/ttrpg-convert-cli#160]
## Description
When using the provided `examples/config/config.json` or `examples/config/config.yaml` files, the contents of the config files are ignored and only 5e SRD content is generated. Any modifications to these files are also ignored.

## Steps to Reproduce
1. Download the latest binary release (2.0.4) and extract it.
2. Copy the 5eTools repo to the `bin` folder.
3. Copy the `examples` folder from the source files to the `bin` folder.
4. Run `ttrpg-convert.exe --index -o dm -c examples/config/config.json -g 5e 5etools-mirror-1.github.io-master/data`

## Expected Behavior
- Output folder structure should be `dm/compendium` with no `rules` folder generated. `rules` folder should instead be under `dm/compendium`.
- Example config should include data from several non-SRD sources, such as the feats from the PHB.
- Background files should be generated with images since the example config specifies to use the template `images-background2md.txt`.

## Actual Behavior
- All config settings are ignored. Only 5e SRD content is generated.

## Root Cause
- The example config files have each game's settings in a separate object/node in the config files (e.g. `{ "5e" : { }, "pf2e" : { } }`. 
- Converting the top-level objects to individual config files (without `5e` or `pf2e` as the top-level object) fixes this issue.

### Examples
Original `config.json`:
```json
{
  "5e" : {
    "from" : [
      "PHB",
      "CRB"
    ],
    "paths" : {
      "compendium" : "/compendium/",
      "rules" : "/compendium/rules/"
    },
    "include" : [
      "race|changeling|mpmm"
    ],
    "includeGroup" : [
      "familiars"
    ],
    "exclude" : [
      "monster|expert|dc",
      "monster|expert|sdw",
      "monster|expert|slw"
    ],
    "excludePattern" : [
      "race|.*|dmg"
    ],
    "template" : {
      "background" : "examples/templates/tools5e/images-background2md.txt"
    },
    "useDiceRoller" : false,
    "full-source" : {
      "book" : [
        "PHB"
      ],
      "adventure" : [
        "LMoP"
      ]
    }
  },
  "pf2e" : {
    "from" : [ ],
    "paths" : {
      "compendium" : null,
      "rules" : null
    },
    "include" : [ ],
    "includeGroup" : [ ],
    "exclude" : [ ],
    "excludePattern" : [ ],
    "template" : { },
    "useDiceRoller" : false,
    "full-source" : {
      "book" : [ ],
      "adventure" : [ ]
    }
  }
}
```

Fixed `config.json` for just the 5e content:
```json
{
  "from": ["PHB", "CRB"],
  "paths": {
    "compendium": "/compendium/",
    "rules": "/compendium/rules/"
  },
  "include": ["race|changeling|mpmm"],
  "includeGroup": ["familiars"],
  "exclude": ["monster|expert|dc", "monster|expert|sdw", "monster|expert|slw"],
  "excludePattern": ["race|.*|dmg"],
  "template": {
    "background": "examples/templates/tools5e/images-background2md.txt"
  },
  "useDiceRoller": false,
  "full-source": {
    "book": ["PHB"],
    "adventure": ["LMoP"]
  }
}
```

## Environment:
- OS: Windows 11
- Version: Tested with binary release 2.0.4 and also by compiling source using Docker.

---

**Comment by ebullient** [comment]
OOPS! Yes. you're right. I should probably just spit those defaults out as two separate files (4 total?).
