### ISSUE TITLE
Homebrew Psion Subclasses

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#172]
Hi @ebullient -- this may be too much of an edge case to worry about, but I've found that while 5etools does a great job of bringing in my homebrewed Psion, it seems to choke on the subclasses. It generates their .md files, but only provides front matter and an initial heading like so:

```markdown
---
obsidianUIMode: preview
cssclass: json5e-class
tags:
- class/psion-inquisitor
- compendium/src/5e/psion
aliases: ["Inquisitor"]
---
# Inquisitor
*Psion: *  
*Source: _Source: LL Psion_*  


## Class Features
```

This is all that is produced. 

I've attached the whole psion json file. I'm running the latest build of the cli. I should probably also note that there are no errors that are spit out by the conversion -- just the files seem to be silently failing to be fully produced. 
[psion.txt](https://github.com/ebullient/ttrpg-convert-cli/files/12113119/psion.txt)

**Comment by ebullient** [comment]
Not a corner case.. just a reference pattern I haven't figured out. Thank you for attaching your homebrew so I can figure it out. :)

**Comment by mclearc** [comment]
I figured out what was wrong -- my bad not yours! Thanks for all the work you do!!
