### ISSUE TITLE
Callout Icon Dark Mode Color Issue

### ISSUE THREAD

**Issue by Nargath** [ebullient/ttrpg-convert-cli#178]
When using any dark theme, and using the pf2-compendium.css file, the symbol used for Reaction does not change to red like the other action symbols do.

Having a look at the css code, I found that on line 153, there's a missing space between the last of the svg data and the fill color data.

Manually adding the line in on my own CSS file allowed the symbol to switch to red on the theme entering dark mode.

**Comment by sigrunixia** [comment]
Oh whoops. I'll get that fixed today :)
