### ISSUE TITLE
🐛 `useDiceRoller` Roll Tables Formatting

### ISSUE THREAD

**Issue by RickCoxDev** [ebullient/ttrpg-convert-cli#195]
I am converting the Curse of Strahd adventure and several of the pages have roll tables with another dice roll for the number of items or monsters. I would like to use the Obsidian Dice Roller with these tables but after converting for example "Chapter 2 The Lands of Barovia" page it comes out to this:
<img width="1099" alt="image" src="https://github.com/ebullient/ttrpg-convert-cli/assets/6799456/37d23e71-6611-4545-9fc7-e9e083cf22a7">

I would expect that the pipe used in the dice formula would be escaped in tables to avoid it being rendered as a separate column. For example  `dice: d12 + d8|avg` (`d12 + d8`) would be `dice: d12 + d8\|avg` (`d12 + d8`)

## Configuration

- **OS**: MacOS
- **CLI version**: 2.2.0
- **CLI type**: jbang

**Sources**:
- enabled sources: PHB,MM,DMG,CoS

**Comment by ebullient** [comment]
Thanks for the report. You're right, and I can now tell. ;)

**Comment by ebullient** [comment]
I have a preliminary fix, but I have to look at some of the more complicated replacements that I disrupted with f32faf425abd7b819665d6b353980caa42ed4e24.
