### ISSUE TITLE
🐛 Things are missing from import

### ISSUE THREAD

**Issue by paulsnoops** [ebullient/ttrpg-convert-cli#200]
Using today's snapshot as a test I selected **every** source but some things are being missed from import, Human for example.

Things shouldn't be skipped whatever sources you select.

I started with a fresh empty folder and used today's snapshot to convert all sources and had a look inside the folders to find some things missing from races (didn't check other folders)

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/18243520/e3391041-f5ae-4934-9f21-d11d2a0c88e9)

## Configuration

Windows 10, JBang

**Sources**:
ALL sources

**Comment by ebullient** [comment]
Linked commit has a serious rewrite of the code used to resolve copied elements and merge races/subraces. This should include correct preservation/drop of 'reprint' markers. If some races still seem to disappear, I think we'll need to take a closer look at the sources in use, and the attributes they set on the races that are disappearing.
