### ISSUE TITLE
🐛 Java CI with Maven Errors

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#207]
I'm getting daily errors from Java CI with Maven, which is unexpected. I'm not doing anything on my end. Here's a screenshot of the error. 

![IMG_2109](https://github.com/ebullient/ttrpg-convert-cli/assets/1502422/f0a9a170-100c-4850-8c0b-be956242cd72)

## Configuration

- **OS**: MacOS M2
- **CLI version**: ttrpg-convert version 299-SNAPSHOT
Git commit: 166117a
Build time: 2023-09-07T09:42:53-0500

- **CLI type**: jar (java or jbang)

**Comment by ebullient** [comment]
Assuming I didn't screw something up (yay for Friday?), this should do the trick: 87abca90189651708e4230496d83daa85ea75a0d

I'll wait for the next time I push some real code, and you can let me know if your build is happy.

**Comment by ebullient** [comment]
Are we good to go? I pushed something the other day..

**Comment by mclearc** [comment]
Sorry! Yes thanks haven't seen any of these errors of late
