### ISSUE TITLE
🐛 antifreeze workflow failed

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#212]
Hate to be the bearer of bad news but I've gotten the following now two nights in a row. 

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/1502422/ae655fa6-d1ab-4ff6-b6e3-2e99c59fe6dc)

**Comment by ebullient** [comment]
no bad news. ;) I may just kill it, and let jitpack freeze
it was unreliable, and I think the GH release is ok.

**Comment by ebullient** [comment]
Should be fixed with 357d76c4564e1b0e2d93db3f8db17bacbe13570e 
Let me know.

**Comment by mclearc** [comment]
Didn't see an error yesterday so I'll close this. Thanks!
