### ISSUE TITLE
🐛 Alignment issues

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#218]
Here's what I get.

🛑 What alignment is this? LNXCG (from sources[monster|aviere|tob2])
🛑 What alignment is this? LNXCG (from sources[monster|cleric of the brew|ccodex])
🛑 What alignment is this? CGCN (from sources[monster|elvish veteran archer|tob])
🛑 What alignment is this? LNLE (from sources[monster|emerald order cult leader|tob])
🛑 What alignment is this? LNYNXCG (from sources[monster|graveslayer|ccodex])
🛑 What alignment is this? CECN (from sources[monster|kappa|ccodex])
🛑 What alignment is this? CECG (from sources[monster|storm maiden|tob2])
🛑 What alignment is this? LNXCG (from sources[monster|temple dog|tob])
🛑 What alignment is this? NELE (from sources[monster|thursir giant|tob])

This is with the current commit & build.

**Comment by ebullient** [comment]
Cool. As mentioned, here are the alignments I recognize: 
```
            case "A" -> "Any alignment";
            case "C" -> "Chaotic";
            case "CE" -> "Chaotic Evil";
            case "CG" -> "Chaotic Good";
            case "CGNE" -> "Chaotic Good or Neutral Evil";
            case "CGNYE" -> "Any Chaotic alignment";
            case "CN" -> "Chaotic Neutral";
            case "N", "NNXNYN" -> "Neutral";
            case "NX" -> "Neutral (law/chaos axis)";
            case "NY" -> "Neutral (good/evil axis)";
            case "NE" -> "Neutral Evil";
            case "NG" -> "Neutral Good";
            case "NGNE", "NENG" -> "Neutral Good or Neutral Evil";
            case "L" -> "Lawful";
            case "LE" -> "Lawful Evil";
            case "LG" -> "Lawful Good";
            case "LN" -> "Lawful Neutral";
            case "LNCE" -> "Lawful Neutral or Chaotic Evil";
            case "LELG" -> "Lawful Evil or Lawful Good";
            case "LELN" -> "Lawful Evil or Lawful Neutral";
            case "LNXCNYE" -> "Any Non-Good alignment";
            case "E", "CELENE", "LNXCE" -> "Any Evil alignment";
            case "LGNYE" -> "Any Non-Chaotic alignment";
            case "NXCGNYE" -> "Any Non-Lawful alignment";
            case "G" -> "Any Good alignment";
            case "U" -> "Unaligned";
```

I think I had some of the now missing ones in there, but I wasn't sure I had them classified properly, so I dropped them out, figuring I'd get asked again with better context.

Given the above list.. what descriptors would you use for these?

- CGCN: "Chaotic Good or Chaotic Neutral"
- CECG: "Chaotic Evil or Chaotic Good"
- LNLE: "Lawful Neutral or Lawful Evil"
- LNXCG: I can't read this. Help?
- LNYNXCG: Is this "Any Non-Evil alignment"?
- NELE: "Neutral Evil or Lawful Evil"

**Comment by mclearc** [comment]
> LNXCG: I can't read this. Help?

Looking at the monsters -- it seems like it is supposed to mean "any Good". 

> LNYNXCG: Is this "Any Non-Evil alignment"?

Yeah the graveslayer is described as "any non-evil" 

The others look right to me.
