### ISSUE TITLE
🐛 Flee Mortals Statblock superscripts and formatting

### ISSUE THREAD

**Issue by scottTomaszewski** [ebullient/ttrpg-convert-cli#232]
The Flee Mortals formatting is a bit unique.  
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/5295276/b28c0801-6971-4f67-83f8-42617a9bbee5)

I believe thats the root cause of the strange formatting.
Here is the rendered statblock
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/5295276/7c0b3133-b842-4a67-a645-697648b45333)

The generated yaml
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/5295276/91c5f76e-ec47-4dc1-83c3-68954795878c)

Generated markdown
[bugbear-channeler-fleemortals.md](https://github.com/ebullient/ttrpg-convert-cli/files/12819021/bugbear-channeler-fleemortals.md)

Template used: https://github.com/scottTomaszewski/5e-markdown/blob/main/monster_template.txt

Flee Mortals json:
https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/creature/MCDM%20Productions;%20Flee,%20Mortals!.json

A clear and concise description of what you expected to happen. A text snippet is helpful.

A clear and concise description of what actually happened. A text snippet is helpful.

## Configuration

- **OS**: Windows, Linux (distro), MacOS, MacOS M1
- **CLI version**: output using the `--version` command
- **CLI type**: jar (java or jbang) or native command

**Sources**:
- enabled sources
- custom templates (attach if possible)

**Comment by ebullient** [comment]
```
"spellcasting": [
				{
					"name": "Spellcasting (Utility)",
					"headerEntries": [
						"In addition to any other spells in this stat block, the channeler can cast the following spells, using Charisma as the spellcasting ability (spell save {@dc 15}):"
					],
					"will": [
						"{@spell light}{@footnote {@sup A}|Casting time: 1 action}",
						"{@spell message}{@footnote {@sup A}|Casting time: 1 action}"
					],
					"daily": {
						"1e": [
							"{@spell detect magic}{@footnote {@sup A}|Casting time: 1 action}",
							"{@spell disguise self}{@footnote {@sup A}|Casting time: 1 action}",
							"{@spell identify}{@footnote {@sup +}|Casting time: Longer than 1 action (see spell description)}"
						]
					},
					"ability": "cha"
				}
			],
```
