### ISSUE TITLE
🐛 Example Inline Monster Templates - Property Missing

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [ebullient/ttrpg-convert-cli#235]
In order for the Statblock/Initiative Tracker plugin to utilise the notes, the following needs to be added to the notes properties. 

monster2md-yamlStatblock-body.txt 
statblock; inline

object2md-yamlStatblock-body.txt
statblock; inline

Without this the plugin ignores the notes and thus cannot use the monsters. 

There was a mild panic attack. 

**Sources**:
not relevant

**Comment by ebullient** [comment]
It does not need statblock-link, right?

**Comment by ObsidianTTRPGProject** [comment]
Statblock link?

**Comment by bernardobenv** [comment]
Sorry, new to anything code-related, I've used the CLI using the Command Prompt on Windows, how do I add said lines to the Notes Properties? Ex: 
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/19866556/fc128fb0-b4b3-404d-afa2-6bd9e1b83704)
