### ISSUE TITLE
🐛 Possible homebrew issues

### ISSUE THREAD

**Issue by NoMansbacon** [ebullient/ttrpg-convert-cli#237]
Hello.
I have made sure all my files are update that being both your CLI and the 5etools mirror. I think it its just the Homebrew files that are coming back with errors. 

This is the current errors i get when running my full config and CLI

```
≡ƒ¢æ Could not find title for OptionalFeatureType: EM from Kobold Press; Deep Magic 14 Elemental Magic.json
≡ƒ¢æ Could not find title for OptionalFeatureType: OF from Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json
≡ƒ¢æ Could not find title for OptionalFeatureType: HRG from Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json
≡ƒÆí Writing files to E:\CLI\5eTools\bin\dm
≡ƒ¢æ Can not find OptionalFeatureType for optional feature progression Blood Curse: {"name":"Blood Curse","featureType":["Blood Curse"],"progression":[0,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,6]}
≡ƒ¢æ What alignment is this? CECN (from sources[monster|kappa|ccodex])
```

As you can tell I'm converting almost all the Kobold Press material and just Matthew mercer's BloodHunter Class.

I have added copies of my Config and the CLI code I'm currently using.

**Config**
https://github.com/NoMansbacon/ObsidianVault/blob/main/dm-sources.json

**CLI Code**
```
ttrpg-convert.exe --index -o dm -c dm-sources.json 5etools-mirror-1.github.io\data "homebrew/creature/Kobold Press; Tome of Beasts.json" "homebrew/creature/Kobold Press; Tome of Beasts 3.json" "homebrew/creature/Kobold Press; Tome of Beasts 2.json" "homebrew/creature/Kobold Press; Creature Codex.json" "homebrew/creature/Kobold Press; Gem Dragons of Faerun.json" "homebrew\class\Matthew Mercer; Blood Hunter.json" "homebrew\collection\Kobold Press; Tome of Heroes.json" "homebrew\collection\Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json" "homebrew\collection\Kobold Press; Deep Magic 01 Clockwork Magic.json" "homebrew\collection\Kobold Press; Deep Magic 03 Void Magic.json" "homebrew\collection\Kobold Press; Deep Magic 04 Illumination Magic.json" "homebrew\collection\Kobold Press; Deep Magic 08 Battle Magic.json" "homebrew\collection\Kobold Press; Deep Magic 13 Dragon Magic.json" "homebrew\collection\Kobold Press; Deep Magic 14 Elemental Magic.json" "homebrew\collection\Kobold Press; Deep Magic 16 Time Magic.json" "homebrew\collection\Kobold Press; Deep Magic 17 Mythos Magic.json"
```

**Comment by ebullient** [comment]
- Have a fix for "What alignment is this? CECN (from sources[monster|kappa|ccodex])"
- These are from missing data in the homebrew (I've opened issues for these):
    - `Could not find title for OptionalFeatureType: EM from Kobold Press; Deep Magic 14 Elemental Magic.json`
    - `Could not find title for OptionalFeatureType: OF from Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json`
    - `Could not find title for OptionalFeatureType: HRG from Kobold Press; Deep Magic Backgrounds, Feats, & Subclasses.json`

    I've downgraded the message to a warning, and will use the abbreviation for the title if the title is missing.
    
- This is a similar issue, I've downgraded to a warning, and will use the name if I can't find anything else (which works out fine)
    - `Can not find OptionalFeatureType for optional feature progression Blood Curse: {"name":"Blood Curse","featureType":["Blood Curse"],"progression":[0,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,6]}`
