### ISSUE TITLE
🐛 FYI ... The following stats did not resolve

### ISSUE THREAD

**Issue by OldManUmby** [ebullient/ttrpg-convert-cli#249]
During my 5E convert, all went pretty well, but these showed up in MacOS Terminal ...

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Battleaxe","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Longbow","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Mace","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Shield","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Shortsword","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"Dragon Slayer Longsword","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"Mithral Chain Mail","style":"inset"}

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"variantrule","source":"ESK","name":"Sidekicks","page":66}

I have some other issues I'll report when I figure them out. THX!

**Comment by ebullient** [comment]
Resolved by #256
