### ISSUE TITLE
🐛 Colons cause issues with property parsing

### ISSUE THREAD

**Issue by NamespaceNick** [ebullient/ttrpg-convert-cli#270]
I was noticing issues with some of my Waterdeep: Dragon Heist character aliases not working, and I believe it was caused by the last line of their properties ("BookSource: Waterdeep: Dragon Heist p. XXX") - I believe the colon is causing an issue with parsing. Further confirmed by the fact that once I delete that last line, Obsidian properly switches to the "Live Preview" and it shows the properties in the righthand side of the window.

- **OS**: MacOS M1

<img width="921" alt="image" src="https://github.com/ebullient/ttrpg-convert-cli/assets/24500120/c064655f-7c6b-4e2b-b880-e668364afecd">

**Comment by ebullient** [comment]
This needs to be fixed in the template. The BookSource field is in a custom template you're using, and the value needs to be quoted.
