### ISSUE TITLE
🐛  Images from the 5e-homebrewery are not local

### ISSUE THREAD

**Issue by namtrah** [ebullient/ttrpg-convert-cli#274]
While building the options for TheGiddyLimit's [Homebrew repo](https://github.com/TheGiddyLimit/homebrew), many of the images are saved in the repo such as https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/_img/yyy/creature/xxx.webp yet they are not copied locally using the CLI.

I would expect that any image that has been stored in the GiddyLimit's master branch should also be copied locally and the image link would then be locally created `![](/compendium/bestiary/aberration/img/chuul.webp#right)`

Actually, the link remained as a https web based link. This means that I need active internet connection for those links, which is not desirable. The link looked like `![](https://raw.githubusercontent.com/TheGiddyLimit/homebrew/master/_img/yyy/creature/xxx.webp#right)`
## Configuration

- **OS**: Linux Ubuntu 22.04.3 LTS
- **CLI version**: output using the `--version` command
```
   ttrpg-convert version 2.2.13
   Git commit: 2ed1387
   Build time: 2023-11-14T17:01:52+0000
```
- **CLI type**: LinuxBrew native command

**Sources**:
- Try Tome of Beasts 3 as an enabled source (not the only one with this error but it is exemplary of the problem).
- no custom templates

```
{
  "from" : [
      "PHB",
      "DMG",
      "ToB3"
  ],
  "paths" : {
    "compendium" : "/",
    "rules" : "/rules/"
  },
  "template": {
      "monster": "ttrpg-convert-cli/examples/templates/tools5e/images-monster2md.txt"
  }
```

**Comment by ebullient** [comment]
Fixed by https://github.com/ebullient/ttrpg-convert-cli/commit/8117d9cf16a7766bfdb4ec2badccb3044baf68d0 (I think. ;) )
