### ISSUE TITLE
🐛 Conversion Issue

### ISSUE THREAD

**Issue by OldManUmby** [ebullient/ttrpg-convert-cli#276]
In my latest conversion, I found the following issues ...

✅ Finished reading data.
🔸 Source BMT is unknown
🔸 Source CoA is unknown
🔸 Source PiP is unknown
🔸 Source HFStCM is unknown
🔸 Source HF is unknown
🔸 Source HFFotM is unknown
💡 Writing files to /Users/oldmanumby/Documents/Gaming/*5eTools2MD/TTRPG-Convert-CLI/bin/Converted
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Battleaxe","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Longbow","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Mace","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Shield","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"+1 Shortsword","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"Dragon Slayer Longsword","style":"inset"}
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"item","source":"DMG","name":"Mithral Chain Mail","style":"inset"}

Also, during the "Wrote" reporting process ...

🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"variantrule","source":"ESK","name":"Sidekicks","page":66}

Otherwise, other sources and files seem fine. THX!

**Comment by OldManUmby** [comment]
Added Title to Issue

**Comment by OldManUmby** [comment]
Interestingly, I don't have any of the mentioned sources in my 'config.5e.json' file.

**Comment by ebullient** [comment]
I have to make a release. I've been getting PRs for the missing sources, but I haven't cut a new release (some of those should go away if you snag the nightly snapshot).

Sources should be compared case-insensitively, but I'll double check that.

**Comment by ebullient** [comment]
> Interestingly, I don't have any of the mentioned sources - except "COA" - in my 'config.5e.json' file. Could this be a capitalization problem with "CoA"?

I try to indicate any sources that weren't recognized ... this suggests (to me) that you have an older version of the CLI, as many of those sources are now known.

**Comment by ebullient** [comment]
@OldManUmby .. Can you clarify which issues still remain?

**Comment by OldManUmby** [comment]
Sorry, just started a new job. I'll check it out this evening and let you know. THX!

**Comment by OldManUmby** [comment]
It looks good at this point. I have all the 5E physical books and even more 5E PDFs I've purchased, and Kickstarted, so my config file is full, and I've added even more as Templates.

**Here are my Terminal results --->>>**

✅ Finished reading config.
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/5etools-mirror-1.github.io/data
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/book/Ghostfire Gaming; Grim Hollow Campaign Guide.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/book/Ghostfire Gaming; Grim Hollow Player's Guide.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/book/MCDM Productions; Kingdoms & Warfare.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/collection/Kobold Press; Deep Magic for 5th Edition.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/collection/Nord Games; Game Master's Toolbox Ultimate Bestiary Revenge of the Horde.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Acheron; Dante's Inferno.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Dragonix; Monster Manual Expanded (v1).json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Dragonix; Monster Manual Expanded II (v2).json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Dragonix; Monster Manual Expanded III.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Frog God Games; Fifth Edition Foes.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Kobold Press; Creature Codex.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Kobold Press; Tome of Beasts.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Kobold Press; Tome of Beasts 2.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Kobold Press; Tome of Beasts 3.json
⏱️ Reading /Users/oldmanumby/Documents/Gaming/*5eTools2MD/Git-Files/homebrew/creature/Nord Games; Ultimate Bestiary The Dreaded Accursed.json
✅ Finished reading data.
💡 Writing files to /Users/oldmanumby/Documents/Gaming/*5eTools2MD/_Converted
🛑 What alignment is this? NECE (from sources[monster|deathpriest exarch of orcus|mme2-v2])
🛑 What alignment is this? NECE (from sources[monster|deathpriest of orcus|mme2-v2])
🛑 What alignment is this? NECE (from sources[monster|high deathpriest of orcus|mme2-v2])
🛑 What alignment is this? NXLGNYE (from sources[monster|tortle monk|mme2-v2])
✅ Wrote 182 reward files.
✅ Wrote 1285 spell files.
✅ Wrote 1824 item files.
✅ Wrote 84 race files.
✅ Wrote 17 deck files.
✅ Wrote 16 classtype files.
✅ Wrote 32 vehicle files.
✅ Wrote 6282 monster files.
✅ Wrote 30 hazard files.
✅ Wrote 127 background files.
✅ Wrote 661 optionalfeature files.
✅ Wrote 148 subclass files.
✅ Wrote 20 trap files.
✅ Wrote 38 subrace files.
✅ Wrote 411 deity files.
✅ Wrote 126 feat files.
✅ Wrote 15 object files.
✅ Wrote 286 notes to compendium.
🔸 statblock entry did not resolve to a markdown link: {"type":"statblock","tag":"variantrule","source":"ESK","name":"Sidekicks","page":66}
✅ Wrote 2295 notes to compendium.
✅ Wrote 137 notes to rules.
🛑 Unable to find image 'img/bestiary/VGM/Shadow Mastiff.jpg'

**<<<--- Not too bad considering the amount imported/converted.**

**Comment by ebullient** [comment]
The two alignment fixes I need to make. 

Unable to find image 'img/bestiary/VGM/Shadow Mastiff.jpg' that one is interesting. I think that's a source error (typos channel in 5eTools)

**Comment by OldManUmby** [comment]
Ya, I figured it's a 5eTools issue too.
