### ISSUE TITLE
🐛 Issues indexing

### ISSUE THREAD

**Issue by AmiiboDB** [ebullient/ttrpg-convert-cli#296]
I made sure I was in my bin folder and in CMD ran the command
`ttrpg-convert.exe --index -o dm 5etools-mirror-1.github.io/data`

It gave me the following error:
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/141281624/4c4bf222-a991-47ef-ace0-c4164f6fdd93)

any ideas?

**Comment by ebullient** [comment]
Sounds like you have an older windows. See #295, which was just closed. 

Have a look at https://github.com/ebullient/ttrpg-convert-cli/blob/main/docs/alternateRun.md, and try either JBang or direct Java invocation.
