### ISSUE TITLE
🐛 Build Error

### ISSUE THREAD

**Issue by mclearc** [ebullient/ttrpg-convert-cli#301]
(cross-posting on Discord) 
Hi ebullient  -- I just pulled the recent changes (up to commit ade393a) and I'm seeing this error:

[ERROR] Failures:
[ERROR]   TemplateDocTest.verifyDocs:34
Expecting empty but was: ["Unable to read lines from /Users/roambot/bin/ttrpg-convert-cli/examples/.DS_Store: java.nio.charset.MalformedInputException: Input length = 1",
    "Unable to read lines from /Users/roambot/bin/ttrpg-convert-cli/examples/templates/.DS_Store: java.nio.charset.MalformedInputException: Input length = 1"]
[INFO]
[ERROR] Tests run: 128, Failures: 1, Errors: 0, Skipped: 1

Looks like it is choking on the .DS_Store files. Is this a "me" problem? Hasn't happened before.

**Comment by ebullient** [comment]
Ah! Yes. I'm looking in example folders now (when I didn't before), as I've added README files there (your feedback on the contents of *those* would be lovely).

Will fix file searching to make sure those files are ignored.
