### ISSUE TITLE
✨ Support / migrate to 5etools-mirror-2

### ISSUE THREAD

**Issue by digitalnoiz** [ebullient/ttrpg-convert-cli#331]
**Describe the solution you'd like**
It would be great to migrate tools and documentation of this project to use the new https://github.com/5etools-mirror-2/5etools-mirror-2.github.io repository to ensure the use of the latest updates.

**Additional context**
At the beginning of the year [Giddy](https://github.com/TheGiddyLimit) posted an announcement to the 5etools discord that 5etools-mirror-1 is being depreciated and that all new content will be posted now to https://github.com/5etools-mirror-2/5etools-mirror-2.github.io.

[New Year, New Mirror](https://discord.com/channels/363680385336606740/470674556709765168/1193207810725527665) - 01/06/2024

> ...
> The old mirror-1 should be considered defunct, and will no longer be receiving updates/maintenance.
> ...
> _[Note that mirror-1 will remain live until the end of February 2024, but we encourage you to switch at your earliest convenience.]_
> ...

With this change: 
- This is a new repo and is not a fork of the [5etools-mirror-1.github.io](https://github.com/5etools-mirror-1/5etools-mirror-1.github.io)
- all image files have been removed from the repo and moved to their own repo: https://github.com/5etools-mirror-2/5etools-img
- This 5etools-img repo also reorganizes the location of monster token images into a bestiary/tokens sub directory.
- All token images have been converted to .webp format.

While these repos have been created / updated, the [5e.tools](https://5e.tools/index.html) website has not been updated to the latest version [v1.199.2](https://github.com/5etools-mirror-2/5etools-img/commit/f82339c57703ee28e1a4f6946b327fcce351f65a) that has been posted in the repo.

**Comment by ebullient** [comment]
YES! Moving to mirror2 is in the plan. Started..
