### ISSUE TITLE
🐛 Treasure being tagged with g, a, or c instead of wealth

### ISSUE THREAD

**Issue by mowgli202** [ebullient/ttrpg-convert-cli#339]
With update 2.3.0, it seems that treasure is being tagged as #item/gear/g or #item/gear/a or #item/gear/c instead of #item/wealth. It is also tagging the details as $G, $C, or $A. 

Treasure was being tagged as item/wealth in previous versions. 

When running the CLI-convert, numerous errors saying 'Unknown item type $G'
Command Line Error:
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/9259493/033d3f4f-c977-47b5-9180-a27f1fbc6c7d)
Vault file:
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/9259493/aa61ae3b-e2f6-4574-ba4d-1c61d48b5a43)

## Configuration

- **OS**: Windows
- **CLI version**: 2.3.0
- **CLI type**: native command

**Comment by ebullient** [comment]
Ew! that's gross!

I wonder if the source data changed. Thanks for the heads up!

**Comment by mowgli202** [comment]
[ttrpg-convert.txt](https://github.com/ebullient/ttrpg-convert-cli/files/14285684/ttrpg-convert.txt)
I hope this is correct.

**Comment by ebullient** [comment]
you did it right =) Thanks!
