### ISSUE TITLE
🐛 error on copying remote images

### ISSUE THREAD

**Issue by TheDSeraph** [ebullient/ttrpg-convert-cli#373]
[ :octagonal_sign: ERR] Unable to copy remote image from https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/ToA/Mwaxanaré.webp to compendium\5e\bestiary\npc\img\mwaxanare.webp (java.io.IOException: Server returned HTTP response code: 400 for URL: https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/ToA/Mwaxanaré.webp)

Same error for Ogrémoch from PotA. Error might be caused by the accented é in the name.

Image should have copied

Server returned HTTP response code: 400 and image was not copied

## Configuration

- **OS**: Windows
- **CLI version**: 2.3.3
- **CLI type**: exe

**Sources**:
- enabled sources: PotA, ToA
- custom templates (attach if possible):

**Comment by ebullient** [comment]
One thing: this should probably be fixed in the 5eTools source. I can't arbitrarily encode image URLs.. because about half of them are already encoded, which means trying to catch the stragglers that leak through.
