### ISSUE TITLE
AC is missing the Armor🐛 

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [ebullient/ttrpg-convert-cli#375]
5e Armor Class is missing the armor and options that help make the AC. 

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/96321415/815235fa-63d9-4c3c-908c-4f16290da262)

AC is presented by the armor options are missing. 
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/96321415/bf95fe42-663e-4577-9ff1-4ccb9611c5f3)

## Configuration
CLI > 5e

**Sources**:
PHB

**Comment by ebullient** [comment]
It is present when you're using plain markdown

Armor Class 16 (natural armor) 

Can you verify for me how or if the Fantasy Statblock YAML format wants these additional characteristics? This is a function of the generated YAML and what FS wants to do with it..

The last I looked, the FS YAML format only accepted an number for the AC.

**Comment by ebullient** [comment]
I'm going to close this for now, because I *can't* fix it. If you use plain markdown rendering (which can still work with the fantasy statblock index, initiative tracker and its encounter builder), then those attributes are available to you.
