### ISSUE TITLE
🐛 DnD5e - Lair Actions and Regional Actions missing from Statblocks and Descriptions

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [ebullient/ttrpg-convert-cli#377]
🐛 DnD5e - Lair Actions and Regional Actions missing from Statblocks and Descriptions

Per link the statblocks should include air Actions and Regional Actions

Lair Actions and Regional Actions are not present at all on a note. 
![image](https://github.com/ebullient/ttrpg-convert-cli/assets/96321415/91512649-e9bc-4534-97c5-f1a9cc39423e)

## Configuration
CLI with book and from sources enabled. 

**Sources**:
- I have used the MM in this example.

**Comment by n21rl** [comment]
Lair actions are not part of the statblock per se and are not included with the Fantasy Stablocks plugin.
I've personally added them to the note by adding this my template:
`{#if resource.legendaryGroup}
{#for group in resource.legendaryGroup}
## {group.key}
{group.desc}
{/for}{/if}`
