### ISSUE TITLE
🐛 Error with remote image copy for new ToB1-2023 source

### ISSUE THREAD

**Issue by rewzone** [ebullient/ttrpg-convert-cli#396]
I received the error below when updating this evening. Looks like the same issue as #373. 

`[ ≡ƒ¢æ ERR] Unable to copy remote image from https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/ToB1-2023/V├ªttir.webp to compendium\bestiary\undead\img\vttir.webp (java.io.IOException: Server returned HTTP response code: 400 for URL: https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/bestiary/ToB1-2023/V├ªttir.webp)`

5etools source: 
https://github.com/5etools-mirror-2/5etools-img/blob/main/bestiary/ToB1-2023/V%C3%A6ttir.webp

https://github.com/5etools-mirror-2/5etools-img/tree/main/bestiary/ToB1-2023

## Configuration

- **OS**: Windows
- **CLI version**: 2.3.5
- **CLI type**: cmd

**Sources**:
- enabled sources
- custom templates (attach if possible)

**Comment by ebullient** [comment]
Should be fixed in 2284ec403f1248b4803f221371cd93982db52cdd
