### ISSUE TITLE
🐛 Deck of Many Things image URLs are not URI-encoded 

### ISSUE THREAD

**Issue by TheOnlyTails** [ebullient/ttrpg-convert-cli#409]
In the Deck of Many Things item note, each card in the deck has an associated image linked to it. However, the URLs to the image source includes spaces, which are not URI-encoded.

The spaces in the URI should be encoded as `%20`s.

```diff
-![](https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/decks/DMG/Deck of Many Things/01-vizier.webp#card)
+![](https://raw.githubusercontent.com/5etools-mirror-2/5etools-img/main/decks/DMG/Deck%20of%20Many%20Things/01-vizier.webp#card)
```

## Configuration

- **OS**: Linux (Fedora 39),
- **CLI version**: v2.3.6
- **CLI type**: native command (installed with homebrew)

**Sources**:
- Player's Handbook, Dungeon Master's Guide, Monster Manual, Elemental Evil Player's Guide, Mordekainen Presents: Monsters of the Multiverse, Strixhaven: A Curriculum of Chaos, Tasha's Cauldron of Everything, Xanathar's Guide to Everything, DM's Screen, Book of Many Things

[ttrpg-convert.log](https://github.com/ebullient/ttrpg-convert-cli/files/14975357/ttrpg-convert.log)

**Comment by TheOnlyTails** [comment]
this is more of a nitpick, but i'd also love to have the actual card names available for when I'm using a physical deck of cards

**Comment by ebullient** [comment]
The card names should be available as the linkable headings in the file.

These paths are the bane of my existence right now. Thank you for reporting.

**Comment by TheOnlyTails** [comment]
By card name I meant Ace of Spades, 2 of Hearts, etc (suit + number)

**Comment by ebullient** [comment]
Oh. One for just a standard deck? Cards for the deck of many things are present (w/ each card as a heading)

**Comment by TheOnlyTails** [comment]
I only see a 1d22 roll table with the flavored names, not standard deck names. this applies to the Deck of Wonder from Book of Many Things too.

**Comment by revilowaldow** [comment]
> Oh. One for just a standard deck?

Constructed from `suit`, `value` & `valueName` information on each individual `card`. Suits vary greatly, wands/cups/swords/stars, major/minor arcana, the official Tarot deck uses Strength/Wisdom/Inteligence/Charisma
Also some cards are named individually such as the Major arcana in tarot decks
See example quote from description of Curse of Strahd's Tarroka Deck:
> Each suit contains cards numbered one through nine, plus a tenth card that is called the master of that suit. A card can be referred to by its suit designation or by its name. For instance, the three of glyphs is also known as the healer, and the wizard card is also known as the master of stars.

**Comment by revilowaldow** [comment]
https://github.com/5etools-mirror-2/5etools-mirror-2.github.io/blob/adec95d4abe14a0a34493121a32dae02ca1a05aa/js/render.js#L10725-L10728
