### ISSUE TITLE
🐛 DnD 5e - not able to add item rarity into the frontmatter

### ISSUE THREAD

**Issue by pwkooij** [ebullient/ttrpg-convert-cli#419]
I am trying to add item rarity in the frontmatter, but I am not able to seem to pick up the information, and instead it throws an error.

I have tried several codes using resource.rarity or resource.detail.rarity, but I'm not able to extract that information

```
---
obsidianUIMode: preview
cssclasses: json5e-item
{#if resource.tags }
tags:
{#for tag in resource.tags}
- {tag}
{/for}
{/if}
aliases: 
- "{resource.name}"
{#if resource.variantAliases }
{resource.variantAliases}
{/if}
NoteIcon: ring
SourceType: Items
BookSource: ["{resource.source}"]
{#if resource.rarity }
Rarity: ["{resource.rarity}"]
{/if}
---
```

I would like the frontmatter output of the item to look like this:

```
---
obsidianUIMode: preview
cssclasses: json5e-item
tags:
- compendium/src/5e/dmg
- ttrpg-cli/item/rarity/uncommon
- ttrpg-cli/item/tier/minor
- ttrpg-cli/item/wondrous/wondrous-item
aliases: 
- "+1 Ammunition"
- "+1 Sling Bullet"
- "+1 Arrow"
- "+1 Modern Bullet"
- "+1 Blowgun Needle"
- "+1 Crossbow Bolt"
- "+1 Energy Cell"
- "+1 Renaissance Bullet"
NoteIcon: ring
SourceType: Items
BookSource: ["Dungeon Master's Guide p. 150. Available in the SRD."]
Rarity: ["uncommon"]
---
```

When I add the text as described above in the template file it results in the following errors for `{resource.rarity}`:
[ 🛑 ERR] io.quarkus.qute.TemplateException: Rendering error: Property "rarity" not found on the base object "dev.ebullient.convert.tools.dnd5e.qute.QuteItem" in expression {resource.rarity}

and for `{resource.detail.rarity}
[ 🛑 ERR] io.quarkus.qute.TemplateException: Rendering error: Property "rarity" not found on the base object "java.lang.String" in expression {resource.detail.rarity}

## Configuration

- **OS**: Linux (Ubuntu 22.04.4 LTS)
- **CLI version**: 
ttrpg-convert version 2.3.8
Git commit: bc7ce40
Build time: 2024-04-18T16:40:43Z
- **CLI type**: brew installation

**Sources**:
- "PHB","DMG","LMoP","MM"
- custom templates (attach if possible)
[images-item2md-Pepijn-test.txt](https://github.com/ebullient/ttrpg-convert-cli/files/15040176/images-item2md-Pepijn-test.txt)

log file with run that included {resource.rarity}
[ttrpg-convert.txt](https://github.com/ebullient/ttrpg-convert-cli/files/15040275/ttrpg-convert.txt)

**Comment by pwkooij** [comment]
Thanks for the clarification! I would love to be able to add the rarity separately in the frontmatter to make it easier to parse with dataview

**Comment by ebullient** [comment]
You can already parse with dataview, as tags are supported natively and you have those.

**Comment by pwkooij** [comment]
I guess I have to go back study on how to use that hehe! Thanks again! And wow you respond fast! Not used to that on github, much appreciated!

**Comment by baxterjo** [comment]
Sorry to ping on a closed issue. But adding rarity as a property for items would be really helpful. Since 5e has default costs for all items as a function of rarity it would be nice to add something like this:

```
{#if resource.cost}
cost: {resource.cost}
{#else if resource.rarity == "common"}
cost: 100 gp
{#else if resource.rarity == "uncommon"}
cost: 400 gp
{#else if resource.rarity == "rare"}
cost: 4000 gp
{#else if resource.rarity == "very rare"}
cost: 40000 gp
{#else if resource.rarity == "legendary"}
cost: 200000 gp
{#else if resource.rarity == "artifact"}
cost: priceless
{/if}
```
