### ISSUE TITLE
Namespace errors and token/images not linking🐛 

### ISSUE THREAD

**Issue by DaniSmol** [ebullient/ttrpg-convert-cli#421]
The main issue is that for specific homebrew certain creatures have namespacing that prevents them form being found, or images for them being retrieved. A good example is "Stone Giant Champion of Ogrémoch" from Monster Manual Expanded III by Dragonix. With the special character "é" being the issue there. 

Additionally some homebrew images are not properly linking to their respective notes. 

FIle found and proper linking of images to notes

## Configuration

- **OS**: Windows 10
- Version: ttrpg-convert-cli-2.3.9
- **CLI type**: Cmd

**Sources**:
- Config
- ToB2 Json for linking
- Monster Manual Expanded III Json for namespace issue. 
[Config.json](https://github.com/ebullient/ttrpg-convert-cli/files/15046450/Config.json)
[Kobold Press; Tome of Beasts 2.json](https://github.com/ebullient/ttrpg-convert-cli/files/15046451/Kobold.Press.Tome.of.Beasts.2.json)
[Dragonix; Monster Manual Expanded III.json](https://github.com/ebullient/ttrpg-convert-cli/files/15046453/Dragonix.Monster.Manual.Expanded.III.json)
[ttrpg-convert.out.txt](https://github.com/ebullient/ttrpg-convert-cli/files/15046463/ttrpg-convert.out.txt)
*
*Note that I added .txt to the end of the out so it would upload here**

-Command used for cmd:
ttrpg-convert.exe --index -o test -c Config.json 5etools-mirror-2.github.io/data

**Comment by ebullient** [comment]
Run with:

```
ttrpg-convert.exe --log --index -o test -c Config.json 5etools-mirror-2.github.io/data
```

And attach ttrpg-convert.out .. please ;)
