### ISSUE TITLE
🐛 CLI creates empty notes

### ISSUE THREAD

**Issue by Drogas058** [ebullient/ttrpg-convert-cli#422]
Some of the note render as blank. This happens for all the the class notes and some other notes. The class notes give an error message within Obsidian. The other notes that render blank, don't give any error, but are just empty.

I followed all the steps from the obisidian ttrpg youtube tutorials. I have rerun the CLI proces multiple times, so I expected the notes to be filled with the correct information.

I have been able to run the CLI proces without any errors from the start so I'm unable to determine by myself in which step of the proces something went wrong.

## Configuration

- **OS**: Windows
- **CLI version**: 2.3.0
- **CLI type**: Native Command Prompt

**Sources**:
- enabled sources: DMG, PHB, MM, LMoP
- I use the templates that come with the CLI

[CLI Output Log.txt](https://github.com/ebullient/ttrpg-convert-cli/files/15047779/CLI.Output.Log.txt)
[dm-config-file.json](https://github.com/ebullient/ttrpg-convert-cli/files/15047780/dm-config-file.json)
I have attached the output generated with the log option and the configuration file I use.
![Schermafbeelding 2024-04-13 123017](https://github.com/ebullient/ttrpg-convert-cli/assets/167615470/5b4fefcc-80c1-4f38-90e6-316f66a62af5)
![Schermafbeelding 2024-04-13 123615](https://github.com/ebullient/ttrpg-convert-cli/assets/167615470/e7da8578-9d8b-4cb8-a7ee-ea37ac796ccd)
I have also attached images from the errors and the faulty notes in Obisidian.

**Comment by ebullient** [comment]
note: you should not need to specify the default templates anymore.

If you view them in source mode, they're also empty?

**Comment by ebullient** [comment]
I think this is a usage error, and no additional information given.

I suggest trying in Obsidian discord channels mentioned in the README for help
