### ISSUE TITLE
🐛 Links to notes and images could not be found

### ISSUE THREAD

**Issue by chawdog** [ebullient/ttrpg-convert-cli#434]
The Bug
Links to existing articles and images show an error message, as images in this report shows. The images are present in my vault, and the path is correct.
For example, the error states that "2-Mechanics/CLI/bestiary/beast/token/ape.webp#token" could not the found, but in my vault, there is an image in that exact path- "2-Mechanics/CLI/beast/token/ape.webp"

I have no templates as of yet.

Configuration file also included in images here:

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/168300709/8e239fc7-d929-4480-9379-205d8c17148d)

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/168300709/08ec3df0-4c42-4f9c-8ff6-788d359cd4e0)

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/168300709/7f431da0-32af-4623-98b0-96ff0fbb7acb)

![image](https://github.com/ebullient/ttrpg-convert-cli/assets/168300709/c9b46e07-0586-43ec-b46c-43a229abc025)

## Configuration

- **OS**: Windows 11
- **CLI version**: 2.3.10

- **CLI type**: jar (java or jbang) or native command

**Sources**:
- enabled sources:
"DMG",
"PHB",
 "MM",
"ToB1-2023",
"MTF",
"TCE",
"XGE",
"VGM",
"AAG",
"DIP",
"MCV1SC",
"RoT",
"MPMM"

**Comment by ebullient** [comment]
You have a misconfiguration somewhere... double check your config file.

These two paths are not the same: 

- "2-Mechanics/CLI/bestiary/beast/token/ape.webp#token" 
- "2-Mechanics/CLI/beast/token/ape.webp"
