### ISSUE TITLE
🐛 Errors when working with version 2.xxx of 5eTools

### ISSUE THREAD

**Issue by CDStevens1** [ebullient/ttrpg-convert-cli#537]
Just started using the CLI tool to convert 5eTools to Obsidian, and got the error message attached every-time I was working with a 2.xxx version of 5eTools. When this is returned, nothing is generated in the output folder.
[Err] "An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5"
[Warn] "Source XPHB is unknown"

Data should have been pulled from the 2024 Players Handbook (XPHB) and the 2014 Players Handbook (PHB).

Error returned for each 5etools instance beginning with 2.0 release. No files placed in output folder

## Configuration

- **OS**:MacOS M1
- **CLI version**: 2.3.18
- **CLI type**: Command

**Sources**:
- PHB, XPHB
- All templates from tool
**Config file**

[config.5e.json](https://github.com/user-attachments/files/17115587/config.5e.json)

[ttrpg-convert.out.txt](https://github.com/user-attachments/files/17115580/ttrpg-convert.out.txt)

<img width="576" alt="Screenshot 2024-09-23 at 8 10 18 PM" src="https://github.com/user-attachments/assets/e1a6deb1-8ef6-41ae-a124-227af58b385c">

**Comment by yZ1v1** [comment]
did you manage to fix it perhaps?

**Comment by jacksonSingleton** [comment]
👍

**Comment by Punchinpaper** [comment]
I am working with the Windows version and CLI returns the same error
[Err] "An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5"

FYI - When working with the 2014 5etools repository everything operates as it should. This only happens with the 2024 version.

**Comment by Punchinpaper** [comment]
could this error be an issue with the template   "spell" : "ttrpg-convert-cli/examples/templates/tools5e/images-spell2md.txt"

**Comment by salvlox** [comment]
> I am working with the Windows version and CLI returns the same error [Err] "An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5"
> 
> FYI - When working with the 2014 5etools repository everything operates as it should. This only happens with the 2024 version.

what do you mean? should I exclude something in the config file or should I download something different from the latest version of the source content?

**Comment by ebullient** [comment]
Note: the reasons these errors are occurring is because of changes due to the 2024 rules. I have not updated the tool to support these changes yet, it is a work in progress.

Please use an older release until I can get the updates shipped.

**Comment by salvlox** [comment]
> Note: the reasons these errors are occurring is because of changes due to the 2024 rules. I have not updated the tool to support these changes yet, it is a work in progress.
> 
> 
> 
> Please use an older release until I can get the updates shipped.

hi erin! thanks you for your work.
which older release should I use?

**Comment by ThaddaeusWiedemer** [comment]
> which older release should I use?

To clarify, I believe @ebullient is talking about using an older release of 5e Tools, prior to the update containing the 2024 rules.

Those rules were added in 5e Tools v2.0.0, the last version without the new rules is v1.210.4

**Comment by Batres3** [comment]
any news on a timeline for this?

**Comment by gabriel-aleixo** [comment]
Hey there, I am still getting this error when trying to convert 5e Tools data containing the 2024 rules. I am running version  2.3.18 of the ttrpg-convert-cli tool, which is the most recent I get using brew on Mac. Is anyone else still having the same issue?

**Comment by Batres3** [comment]
@gabriel-aleixo The latest release (in the releases page) is from 5 months ago, it has not been updated to the newest version, if you want 2024 support you'll have to compile it yourself, you can see how [here](https://github.com/ebullient/ttrpg-convert-cli/blob/main/docs%2FalternateRun.md)

**Comment by gabriel-aleixo** [comment]
Thanks a lot @Batres3 !
