### ISSUE TITLE
🐛 Repository Taken down

### ISSUE THREAD

**Issue by WolfQuery** [ebullient/ttrpg-convert-cli#538]
Every time I attempt to clone the repository git gives me the error that the DnD 5e repo was taken down due to a DMCA report by WotC:

PS C:\Users\qwert\Desktop\ttrpg-convert-cli-2.3.18-windows-x86_64\ttrpg-convert-cli-2.3.18-windows-x86_64\bin> git clone
 --depth 1 https://github.com/5etools-mirror-2/5etools-mirror-2.github.io.git
Cloning into '5etools-mirror-2.github.io'...
info: please complete authentication in your browser...
remote: Repository unavailable due to DMCA takedown.
remote: See the takedown notice for more details:
remote:   https://github.com/github/dmca/blob/master/2024/08/2024-08-07-wizards-of-the-coast.md.
fatal: unable to access 'https://github.com/5etools-mirror-2/5etools-mirror-2.github.io.git/': The requested URL returned error: 403

![image](https://github.com/user-attachments/assets/66993404-1601-46be-8bd3-5490af979b0d)

**Comment by ebullient** [comment]
Yes, this is known and is not a bug with this application. I will try to clarify in the docs that you need to point to the 5eTools data directory.
