### ISSUE TITLE
Move Away from Admonition

### ISSUE THREAD

**Issue by jacksonSingleton** [ebullient/ttrpg-convert-cli#543]
Adomonition is on maintenance mode and native Obsidian callouts should be used where possible

Obsidian custom callouts can be generated based on the JSON files provided. I haven't checked for parity with the Lucide icons yet, but it should theoretically be possible. Adominition is on maintenance mode, and plugin reduction is always nice when possible. Will start a PR for this when I get a chance, but just dropping this here if someone is quicker than I.

See: https://help.obsidian.md/Editing+and+formatting/Callouts

**Comment by jacksonSingleton** [comment]
Ehh, looking into this more. Just utilizing lucide icons wouldn't work for this. Possible to create a mapping to svg sources, but will need to be looked into further

**Comment by ebullient** [comment]
Admonitions is feature complete. Maintenance mode is not a problem
