### ISSUE TITLE
🐛 An error occurred: NullPointerException.

### ISSUE THREAD

**Issue by Dawe5ome** [ebullient/ttrpg-convert-cli#565]
[config-file-name.json](https://github.com/user-attachments/files/17561770/config-file-name.json)
[ttrpg-convert.out.txt](https://github.com/user-attachments/files/17561771/ttrpg-convert.out.txt)

When running the CLI i constantly get presented with the NullPointerException error. I have been using [5etools-2014-src](https://github.com/5etools-mirror-3/5etools-2014-src) and [5etools-2014-img](https://github.com/5etools-mirror-3/5etools-2014-img)

Run with --debug for details.

It should properly extract everything like mentioned at step 2.

This is what I always get.

C:\CLI\5eTools\bin>ttrpg-convert --index -o dm 5etools-mirror-3.github.io
[ Γ£à  OK] Finished reading config.
ΓÅ▒∩╕Å  Reading C:\CLI\5eTools\bin\5etools-mirror-3.github.io
[≡ƒö╕ WARN] Could not find title for OptionalFeatureType: TT from unknown/core
[ Γ£à  OK] Finished reading data.
[ ≡ƒ¢æ ERR] An error occurred: NullPointerException.

Run with --debug for details.

## Configuration

- **OS**: Using Windows 11
- **CLI version**: ttrpg-convert version 2.3.18/Git commit: ed56f76/Build time: 2024-07-27T02:01:31Z
- **CLI type**: [ttrpg-convert-cli-2.3.18-windows-x86_64.zip](https://github.com/ebullient/ttrpg-convert-cli/releases/download/2.3.18/ttrpg-convert-cli-2.3.18-windows-x86_64.zip)

**Sources**:
- enabled sources
- custom templates (attach if possible)

**Comment by sundeer** [comment]
same here

**Comment by human358** [comment]
I ran into the same issue, both on linux and windows, this is what fixed it for me :

- Change repo and use 5etools-src instead of 5etools-2014-src
- Go to the releases and get the version 1.210.4 (scroll down, then go to page 2), filename is 5etools-v1.210.4.zip

Using this solved the issue instantly, I had the exact same error :

```bash
🔧 	race|genasi (water)|mpmm :: subrace|genasi (water)|genasi|mpmm
[ 🛑 ERR] An error occurred: NullPointerException.
```

**Comment by ebullient** [comment]
Did you run with --log? I'll update my help instructions to suggest running with --log so I have more to work with in the bug report.

**Comment by Deltamir** [comment]
Hi, I ran on the same issue. Hope I can help provide some more details : Here is my [config.json](https://github.com/user-attachments/files/17757517/config.json) and here is the log file : [ttrpg-convert.out.txt](https://github.com/user-attachments/files/17757534/ttrpg-convert.out.txt)
The command was : `./ttrpg-convert --index -o extract /5etools-mirror-2014/data/ -c config.json --debug --log`

**Comment by ebullient** [comment]
you followed @human358 instructions? Even the 5etools-mirror-2014 data format has drifted..

**Comment by ebullient** [comment]
Closing, as against 5etools-mirror-2014
