### ISSUE TITLE
🐛 Bug when using snapshot 299

### ISSUE THREAD

**Issue by scoonts3** [ebullient/ttrpg-convert-cli#580]
I wanted to test out the branch newthings and grabbed snapshot_299.  When running either the default config file or my own, I got the error below after entering " ttrpg-convert --index --debug -o dm 5etools-mirror-2.github.io/data" into powershell

??  Reading C:\Users\scoonts3\Documents\CLI\5eTools\bin\5etools-mirror-2.github.io\data
? ? C:\Users\scoonts3\Documents\CLI\5eTools\bin\5etools-mirror-2.github.io\data\bestiary
? ? C:\Users\scoonts3\Documents\CLI\5eTools\bin\5etools-mirror-2.github.io\data\spells
? ? C:\Users\scoonts3\Documents\CLI\5eTools\bin\5etools-mirror-2.github.io\data\class
[? WARN] Could not find title for OptionalFeatureType: TT from unknown/core
[ ?  OK] Finished reading data.
? 2 subraces found for race|vampire|psz
?       race|vampire (zendikar)|psz :: subrace|vampire (zendikar)|vampire|psz
?       race|vampire (ixalan)|psx :: subrace|vampire (ixalan)|vampire|psz|psx
? 3 subraces found for race|dragonborn|phb
?       race|dragonborn (draconblood)|egw :: subrace|dragonborn (draconblood)|dragonborn|phb|egw
?       race|dragonborn|phb :: subrace|dragonborn|dragonborn|phb
?       race|dragonborn (ravenite)|egw :: subrace|dragonborn (ravenite)|dragonborn|phb|egw
? 8 subraces found for race|human|phb
?       race|human (mark of making)|erlw :: subrace|human (mark of making)|human|phb|erlw
?       race|human (mark of passage)|erlw :: subrace|human (mark of passage)|human|phb|erlw
?       race|human (mark of handling)|erlw :: subrace|human (mark of handling)|human|phb|erlw
?       race|human (variant)|phb :: subrace|human (variant)|human|phb
?       race|human|phb :: subrace|human|human|phb
?       race|human (mark of sentinel)|erlw :: subrace|human (mark of sentinel)|human|phb|erlw
?       race|human (variant; mark of finding)|erlw :: subrace|human (variant; mark of finding)|human|phb|erlw
?       race|human (keldon)|psd :: subrace|human (keldon)|human|phb|psd
? 14 subraces found for race|tiefling|phb
?       race|tiefling (baalzebul)|mtf :: subrace|tiefling (baalzebul)|tiefling|phb|mtf
?       race|tiefling (variant; devil's tongue)|scag :: subrace|tiefling (variant; devil's tongue)|tiefling|phb|scag
?       race|tiefling (variant; winged)|scag :: subrace|tiefling (variant; winged)|tiefling|phb|scag
?       race|tiefling (mephistopheles)|mtf :: subrace|tiefling (mephistopheles)|tiefling|phb|mtf
?       race|tiefling (dispater)|mtf :: subrace|tiefling (dispater)|tiefling|phb|mtf
?       race|tiefling (levistus)|mtf :: subrace|tiefling (levistus)|tiefling|phb|mtf
?       race|tiefling (variant; hellfire)|scag :: subrace|tiefling (variant; hellfire)|tiefling|phb|scag
?       race|tiefling (glasya)|mtf :: subrace|tiefling (glasya)|tiefling|phb|mtf
?       race|tiefling|phb :: subrace|tiefling|tiefling|phb
?       race|tiefling (mammon)|mtf :: subrace|tiefling (mammon)|tiefling|phb|mtf
?       race|tiefling (asmodeus)|mtf :: subrace|tiefling (asmodeus)|tiefling|phb|mtf
?       race|tiefling (zariel)|mtf :: subrace|tiefling (zariel)|tiefling|phb|mtf
?       race|tiefling (variant; infernal legacy)|scag :: subrace|tiefling (variant; infernal legacy)|tiefling|phb|scag
?       race|tiefling (fierna)|mtf :: subrace|tiefling (fierna)|tiefling|phb|mtf
? 4 subraces found for race|dwarf|phb
?       race|dwarf (hill)|phb :: subrace|dwarf (hill)|dwarf|phb
?       race|dwarf (mark of warding)|erlw :: subrace|dwarf (mark of warding)|dwarf|phb|erlw
?       race|dwarf (duergar)|mtf :: subrace|dwarf (duergar)|dwarf|phb|mtf
?       race|dwarf (mountain)|phb :: subrace|dwarf (mountain)|dwarf|phb
? 4 subraces found for race|shifter|erlw
?       race|shifter (beasthide)|erlw :: subrace|shifter (beasthide)|shifter|erlw
?       race|shifter (longtooth)|erlw :: subrace|shifter (longtooth)|shifter|erlw
?       race|shifter (swiftstride)|erlw :: subrace|shifter (swiftstride)|shifter|erlw
?       race|shifter (wildhunt)|erlw :: subrace|shifter (wildhunt)|shifter|erlw
? 2 subraces found for race|luma|hwcs
?       race|luma (sera)|hwcs :: subrace|luma (sera)|luma|hwcs
?       race|luma (sable)|hwcs :: subrace|luma (sable)|luma|hwcs
? 9 subraces found for race|elf|phb
?       race|elf (wood)|phb :: subrace|elf (wood)|elf|phb
?       race|elf (sea)|mtf :: subrace|elf (sea)|elf|phb|mtf
?       race|elf (drow)|phb :: subrace|elf (drow)|elf|phb
?       race|elf (shadar-kai)|mtf :: subrace|elf (shadar-kai)|elf|phb|mtf
?       race|elf (mark of shadow)|erlw :: subrace|elf (mark of shadow)|elf|phb|erlw
?       race|elf (high)|phb :: subrace|elf (high)|elf|phb
?       race|elf (pallid)|egw :: subrace|elf (pallid)|elf|phb|egw
?       race|elf (eladrin)|mtf :: subrace|elf (eladrin)|elf|phb|mtf
?       race|elf (eladrin)|dmg :: subrace|elf (eladrin)|elf|phb|dmg
? 2 subraces found for race|half-orc|phb
?       race|half-orc (variant; mark of finding)|erlw :: subrace|half-orc (variant; mark of finding)|half-orc|phb|erlw
?       race|half-orc|phb :: subrace|half-orc|half-orc|phb
? 5 subraces found for race|gnome|phb
?       race|gnome (deep/svirfneblin)|scag :: subrace|gnome (deep/svirfneblin)|gnome|phb|scag
?       race|gnome (forest)|phb :: subrace|gnome (forest)|gnome|phb
?       race|gnome (rock)|phb :: subrace|gnome (rock)|gnome|phb
?       race|gnome (mark of scribing)|erlw :: subrace|gnome (mark of scribing)|gnome|phb|erlw
?       race|gnome (deep)|mtf :: subrace|gnome (deep)|gnome|phb|mtf
? 2 subraces found for race|gallus|hwcs
?       race|gallus (bright)|hwcs :: subrace|gallus (bright)|gallus|hwcs
?       race|gallus (huden)|hwcs :: subrace|gallus (huden)|gallus|hwcs
? 2 subraces found for race|strig|hwcs
?       race|strig (swift)|hwcs :: subrace|strig (swift)|strig|hwcs
?       race|strig (stout)|hwcs :: subrace|strig (stout)|strig|hwcs
? 3 subraces found for race|aasimar|vgm
?       race|aasimar (scourge)|vgm :: subrace|aasimar (scourge)|aasimar|vgm
?       race|aasimar (fallen)|vgm :: subrace|aasimar (fallen)|aasimar|vgm
?       race|aasimar (protector)|vgm :: subrace|aasimar (protector)|aasimar|vgm
? 2 subraces found for race|gith|mtf
?       race|gith (githyanki)|mtf :: subrace|gith (githyanki)|gith|mtf
?       race|gith (githzerai)|mtf :: subrace|gith (githzerai)|gith|mtf
? 2 subraces found for race|cervan|hwcs
?       race|cervan (pronghorn)|hwcs :: subrace|cervan (pronghorn)|cervan|hwcs
?       race|cervan (grove)|hwcs :: subrace|cervan (grove)|cervan|hwcs
? 2 subraces found for race|raptor|hwcs
?       race|raptor (mistral)|hwcs :: subrace|raptor (mistral)|raptor|hwcs
?       race|raptor (maran)|hwcs :: subrace|raptor (maran)|raptor|hwcs
? 7 subraces found for race|half-elf|phb
?       race|half-elf (variant; aquatic elf descent)|scag :: subrace|half-elf (variant; aquatic elf descent)|half-elf|phb|scag
?       race|half-elf (variant; mark of detection)|erlw :: subrace|half-elf (variant; mark of detection)|half-elf|phb|erlw
?       race|half-elf (variant; drow descent)|scag :: subrace|half-elf (variant; drow descent)|half-elf|phb|scag
?       race|half-elf (variant; mark of storm)|erlw :: subrace|half-elf (variant; mark of storm)|half-elf|phb|erlw
?       race|half-elf (variant; moon elf or sun elf descent)|scag :: subrace|half-elf (variant; moon elf or sun elf descent)|half-elf|phb|scag
?       race|half-elf (variant; wood elf descent)|scag :: subrace|half-elf (variant; wood elf descent)|half-elf|phb|scag
?       race|half-elf|phb :: subrace|half-elf|half-elf|phb
? 2 subraces found for race|aven|psa
?       race|aven (ibis-headed)|psa :: subrace|aven (ibis-headed)|aven|psa
?       race|aven (hawk-headed)|psa :: subrace|aven (hawk-headed)|aven|psa
? 2 subraces found for race|corvum|hwcs
?       race|corvum (dusk)|hwcs :: subrace|corvum (dusk)|corvum|hwcs
?       race|corvum (kindled)|hwcs :: subrace|corvum (kindled)|corvum|hwcs
? 5 subraces found for race|merfolk|psz
?       race|merfolk (zendikar; cosi creed)|psz :: subrace|merfolk (zendikar; cosi creed)|merfolk|psz
?       race|merfolk (zendikar; emeria creed)|psz :: subrace|merfolk (zendikar; emeria creed)|merfolk|psz
?       race|merfolk (zendikar; ula creed)|psz :: subrace|merfolk (zendikar; ula creed)|merfolk|psz
?       race|merfolk (ixalan; blue)|psx :: subrace|merfolk (ixalan; blue)|merfolk|psz|psx
?       race|merfolk (ixalan; green)|psx :: subrace|merfolk (ixalan; green)|merfolk|psz|psx
? 2 subraces found for race|elf (kaladesh)|psk
?       race|elf (kaladesh; vahadar)|psk :: subrace|elf (kaladesh; vahadar)|elf (kaladesh)|psk
?       race|elf (kaladesh; bishatar and tirahar)|psk :: subrace|elf (kaladesh; bishatar and tirahar)|elf (kaladesh)|psk
? 4 subraces found for race|genasi|eepc
?       race|genasi (water)|eepc :: subrace|genasi (water)|genasi|eepc
?       race|genasi (air)|eepc :: subrace|genasi (air)|genasi|eepc
?       race|genasi (earth)|eepc :: subrace|genasi (earth)|genasi|eepc
?       race|genasi (fire)|eepc :: subrace|genasi (fire)|genasi|eepc
? 6 subraces found for race|halfling|phb
?       race|halfling (lotusden)|egw :: subrace|halfling (lotusden)|halfling|phb|egw
?       race|halfling (mark of healing)|erlw :: subrace|halfling (mark of healing)|halfling|phb|erlw
?       race|halfling (mark of hospitality)|erlw :: subrace|halfling (mark of hospitality)|halfling|phb|erlw
?       race|halfling (stout)|phb :: subrace|halfling (stout)|halfling|phb
?       race|halfling (ghostwise)|scag :: subrace|halfling (ghostwise)|halfling|phb|scag
?       race|halfling (lightfoot)|phb :: subrace|halfling (lightfoot)|halfling|phb
? 4 subraces found for race|goblin|psz
?       race|goblin (zendikar; lavastep tribe)|psz :: subrace|goblin (zendikar; lavastep tribe)|goblin|psz
?       race|goblin (ixalan)|psx :: subrace|goblin (ixalan)|goblin|psz|psx
?       race|goblin (zendikar; tuktuk tribe)|psz :: subrace|goblin (zendikar; tuktuk tribe)|goblin|psz
?       race|goblin (zendikar; grotag tribe)|psz :: subrace|goblin (zendikar; grotag tribe)|goblin|psz
? 3 subraces found for race|elf (zendikar)|psz
?       race|elf (zendikar; mul daya nation)|psz :: subrace|elf (zendikar; mul daya nation)|elf (zendikar)|psz
?       race|elf (zendikar; tajuru nation)|psz :: subrace|elf (zendikar; tajuru nation)|elf (zendikar)|psz
?       race|elf (zendikar; joraga nation)|psz :: subrace|elf (zendikar; joraga nation)|elf (zendikar)|psz
? 4 subraces found for race|human (innistrad)|psi
?       race|human (innistrad; gavony)|psi :: subrace|human (innistrad; gavony)|human (innistrad)|psi
?       race|human (innistrad; kessig)|psi :: subrace|human (innistrad; kessig)|human (innistrad)|psi
?       race|human (innistrad; nephalia)|psi :: subrace|human (innistrad; nephalia)|human (innistrad)|psi
?       race|human (innistrad; stensia)|psi :: subrace|human (innistrad; stensia)|human (innistrad)|psi
? 4 subraces found for race|genasi|mpmm
?       race|genasi (earth)|mpmm :: subrace|genasi (earth)|genasi|mpmm
?       race|genasi (air)|mpmm :: subrace|genasi (air)|genasi|mpmm
?       race|genasi (fire)|mpmm :: subrace|genasi (fire)|genasi|mpmm
?       race|genasi (water)|mpmm :: subrace|genasi (water)|genasi|mpmm
[? WARN] Source XDMG is unknown
[? WARN] Source XPHB is unknown
[? WARN] Source XMM is unknown
[ ? ERR] An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5.

Run with --debug for details.
java.lang.IllegalArgumentException: Unknown HP pattern: 50 + 10 for each spell level above 5
        at dev.ebullient.convert.tools.dnd5e.Json2QuteMonster$MonsterHp.<init>(Json2QuteMonster.java:605)
        at dev.ebullient.convert.tools.dnd5e.Json2QuteMonster$ConjuredMonster.<init>(Json2QuteMonster.java:502)
        at dev.ebullient.convert.tools.dnd5e.Json2QuteMonster.createVariant(Json2QuteMonster.java:482)
        at dev.ebullient.convert.tools.dnd5e.Json2QuteMonster.findConjuredMonsterVariants(Json2QuteMonster.java:472)
        at dev.ebullient.convert.tools.dnd5e.Json2QuteMonster.findMonsterVariants(Json2QuteMonster.java:390)
        at dev.ebullient.convert.tools.dnd5e.Tools5eIndex.findVariants(Tools5eIndex.java:592)
        at dev.ebullient.convert.tools.dnd5e.Tools5eIndex.prepare(Tools5eIndex.java:435)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:238)
        at dev.ebullient.convert.RpgDataConvertCli.call(RpgDataConvertCli.java:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at dev.ebullient.convert.RpgDataConvertCli.executionStrategy(RpgDataConvertCli.java:273)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at dev.ebullient.convert.RpgDataConvertCli.run(RpgDataConvertCli.java:285)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:143)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

My version of ttrpg-config: I used the 299-snapshot and installed it with jbang
ttrpg-convert version 299-SNAPSHOT
Git commit: 233c74b
Build time: 2024-11-11T20:20:51Z

**Comment by ebullient** [comment]
An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5. 

See #532 and #537 ..
You're waiting on #579
