### ISSUE TITLE
🐛 When I try to run ttrpg-convert, I receive the following error message in cmd: I have tried using this with the previous version of ttrpg-convert as well as the new version. I have downloaded the 2.5.4 versions of the 5etools and 5etools-w-img. 

### ISSUE THREAD

**Issue by swellsby** [ebullient/ttrpg-convert-cli#585]
When I try to run ttrpg-convert I get the error message below and it does not deposit any files into the DM folder.

[≡ƒö╕ WARN] Source XDMG is unknown
[≡ƒö╕ WARN] Source XPHB is unknown
[≡ƒö╕ WARN] Source XMM is unknown
[ ≡ƒ¢æ ERR] An error occurred: Unknown HP pattern: 50 + 10 for each spell level above 5.

I have used ttrpg-convert successfully with the 2014 version of 5etools but with the new 2.5.4 version, I can't seem to make any progress due to the error message above. I was using this command line: ttrpg-convert.exe --index -o dm -c Newsources.json 5etools-mirror-2.github.io/data where Newsources.json just has a very straightforward call for the new XDMG and XPHB sources.

**Comment by ebullient** [comment]
known. working on it.
