### ISSUE TITLE
🐛 Images Links broken

### ISSUE THREAD

**Issue by Snotmwd** [ebullient/ttrpg-convert-cli#593]
### Describe the bug

Images import seems to generate broken links between notes and imported images. They are correctly stored in the vault, under '[ParentFolder]/img' . But referenced in the note '[ParentFolder]/note' like that: ![](/CLI/backgrounds/img/artisan.webp#right).
[ttrpg-convert.out.txt](https://github.com/user-attachments/files/18110531/ttrpg-convert.out.txt)
[cli-config.json](https://github.com/user-attachments/files/18110535/cli-config.json)
[artisan-xphb.md](https://github.com/user-attachments/files/18110541/artisan-xphb.md)

### Expected Behavior

i expected images links to be like ![path/to/img.webp] or ![](path/to/img.webp)

### TTRPG CLI Version

ttrpg-convert version 299-SNAPSHOT

### Which Operating Systems have you experienced this on?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [x] Windows

**Comment by ebullient** [comment]
Thank you for excellent bug report. Appreciated.

**Comment by ebullient** [comment]
This `![](/CLI/backgrounds/img/artisan.webp#right)` is a valid markdown link. Is the image visible in the vault? Based on what I can see, it should be.

Generated content does not use relative paths for images (they are copied only once, and are sometimes reused)

**Comment by Snotmwd** [comment]
Images were not shown because i made an error: opened CLI folder as vault to not import in my main. So CLI was not root folder and Obsidian could not find the path.

Sorry for the inconvenience, and thank you for the work you've done
